/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrganizationDump {
  createdAt?: Date;
  email?: string;
  fax?: string;
  id?: number;
  locationId?: number;
  logoId?: number;
  name?: string;
  phone?: string;
  shortName?: string;
  updatedAt?: Date;
  url?: string;
}
