/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Image } from './image';
import { Location } from './location';
import { OrganizationRef } from './organizationRef';

export interface Place {
  readonly createdAt?: Date;
  description?: string;
  readonly id?: number;
  location?: Location;
  name: string;
  organization?: OrganizationRef;
  photo?: Image;
  readonly updatedAt?: Date;
  url?: string;
}
